<?php
define("CONTROLLER_PATH","Application/controller");
define("PUBLIC_PATH","Application/public/");
define("VIEWS_PATH","Application/view");
define("MODELS_PATH","Application/models");
define("DB_HOST","localhost");
define("DB_NAME","test");
define("SITE_URL","http://localhost/code/Framework");
define("DB_USERNAME","root");
define("DB_PASSWORD","");